"""Filesystem backend — the default when no object store is configured.

Previously "no object store" meant the original bytes were simply dropped: the
image was still understood and its description kept, but the source was gone.
That is a defensible trade for a server with an object store one config away,
and a bad default for a library someone just installed. Files now land on disk.

The method surface mirrors the object store exactly, and the key layout is
produced by the same shared helper, so the same bytes land at the same key on
either backend and nothing upstream can tell the difference.
"""

from __future__ import annotations

import hashlib
import os
import shutil
from pathlib import Path

from loguru import logger

from ._common import (
    MediaNotFoundError, MediaStoreError, StoredImage, StoredVideo,
    content_key, validate_audio, validate_image, validate_video,
)


class LocalMediaStore:
    """Content-addressed media on the local filesystem."""

    def __init__(self, *, root: str | Path, prefix: str = "",
                 base_url: str = "") -> None:
        self.root = Path(root).expanduser()
        self.prefix = prefix
        # Public prefix under which these files are reachable over HTTP, if
        # anything serves them. Optional for images, which are inlined as
        # base64 for vision; required for video, see sign_url.
        self.base_url = base_url.rstrip("/")
        self.root.mkdir(parents=True, exist_ok=True)

    # —— internals ——
    def _path(self, key: str) -> Path:
        # Keys are generated by content_key and are never user input, but a
        # traversal here would write outside the data directory, so check anyway.
        p = (self.root / key).resolve()
        root = str(self.root.resolve())
        # The separator matters: a bare startswith would also pass a sibling
        # whose name shares the prefix (/data/media2 under root /data/media).
        if not (str(p) == root or str(p).startswith(root + os.sep)):
            raise MediaStoreError(f"refusing to write outside the data directory: {key!r}")
        return p

    def _write(self, key: str, data: bytes, *, kind: str, owner: str) -> None:
        path = self._path(key)
        if path.exists():
            logger.debug(f"media already present, skipping write: {key}")
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        # Write to a temporary name and rename: a crash mid-write would
        # otherwise leave a truncated file at a content-addressed key, and
        # content addressing means nothing would ever overwrite it.
        tmp = path.with_suffix(path.suffix + ".part")
        tmp.write_bytes(data)
        tmp.replace(path)
        logger.info(f"stored {kind} owner={owner} key={key} bytes={len(data)}")

    # —— writes ——
    def save_image(self, data: bytes, *, owner: str, content_type: str = "") -> StoredImage:
        detected, extension = validate_image(data, content_type)
        sha256 = hashlib.sha256(data).hexdigest()
        key = content_key(self.prefix, owner, sha256, extension)
        self._write(key, data, kind="image", owner=owner)
        return StoredImage(key=key, sha256=sha256, content_type=detected, byte_size=len(data))

    def save_video(self, data: bytes, *, owner: str, content_type: str = "") -> StoredVideo:
        detected, extension = validate_video(data, content_type)
        sha256 = hashlib.sha256(data).hexdigest()
        key = content_key(self.prefix, owner, sha256, extension, subdir="clip")
        self._write(key, data, kind="video", owner=owner)
        return StoredVideo(key=key, sha256=sha256, content_type=detected, byte_size=len(data))

    def save_audio(self, data: bytes, *, owner: str) -> str:
        validate_audio(data)
        sha256 = hashlib.sha256(data).hexdigest()
        key = content_key(self.prefix, owner, sha256, ".wav", subdir="voice")
        self._write(key, data, kind="audio", owner=owner)
        return key

    # —— reads ——
    def object_size(self, key: str) -> int:
        try:
            return self._path(key).stat().st_size
        except OSError as exc:
            raise MediaNotFoundError(key) from exc

    def read_bytes(self, key: str) -> bytes:
        try:
            return self._path(key).read_bytes()
        except OSError as exc:
            raise MediaNotFoundError(key) from exc

    def exists(self, key: str) -> bool:
        try:
            return self._path(key).exists()
        except MediaStoreError:
            return False

    def sign_url(self, key: str) -> str:
        """A URL for this object. There is nothing to sign on a local disk.

        With PERSONOS_MEDIA_BASE_URL set, returns a URL under it. Without it,
        images still work — vision inlines the bytes as base64 — but **video
        does not**, because the screenplay pass hands the URL to a model that
        fetches it server-side, and no remote model can open a file:// path.

        Raising for video is deliberate. Returning a file:// URL would surface
        as an opaque failure inside the model call, several layers from the
        actual cause.
        """
        if self.base_url:
            return f"{self.base_url}/{key}"
        if "/clip/" in key:
            raise MediaStoreError(
                f"video at {key!r} cannot be handed to a remote multimodal model from "
                "local media storage: set PERSONOS_MEDIA_BASE_URL to a publicly "
                "reachable prefix serving the media directory, or configure object "
                "storage with PERSONOS_MEDIA_BACKEND=oss")
        return self._path(key).as_uri()

    # —— housekeeping ——
    def delete(self, key: str) -> None:
        """Not part of the store protocol; useful for tests and cleanup tools."""
        self._path(key).unlink(missing_ok=True)

    def clear(self) -> None:
        shutil.rmtree(self.root, ignore_errors=True)
        self.root.mkdir(parents=True, exist_ok=True)
