-- Generated by `personos schema --mysql`. Do not edit by hand:
-- the source of truth is personos/storage/db/ddl.py.

CREATE TABLE IF NOT EXISTS users (
        token       VARCHAR(64) NOT NULL,
        user_id     VARCHAR(128) NOT NULL,
        created_at  VARCHAR(64) NOT NULL,
        PRIMARY KEY (token),
        UNIQUE KEY uq_users_user (user_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS evidence (
        id          VARCHAR(64) NOT NULL,
        user_id     VARCHAR(128) NOT NULL DEFAULT '',
        sha256      VARCHAR(64),
        holder      VARCHAR(64),
        modality    VARCHAR(16),
        captured_at VARCHAR(64),
        payload     MEDIUMTEXT NOT NULL,
        embedding   MEDIUMBLOB,
        PRIMARY KEY (id),
        KEY idx_evidence_user_sha (user_id, sha256)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS atoms (
        id           VARCHAR(64) NOT NULL,
        user_id      VARCHAR(128) NOT NULL DEFAULT '',
        memcell_id   VARCHAR(64),
        chain_id     VARCHAR(64),
        prev_atom_id VARCHAR(64),
        next_atom_id VARCHAR(64),
        object_type  VARCHAR(32),
        holder       VARCHAR(64),
        recorded_at  VARCHAR(64),
        updated_at   VARCHAR(64),
        payload      MEDIUMTEXT NOT NULL,
        embedding    MEDIUMBLOB,
        PRIMARY KEY (id),
        KEY idx_atoms_cell (user_id, memcell_id),
        KEY idx_atoms_chain (user_id, chain_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS atom_chains (
        id           VARCHAR(64) NOT NULL,
        user_id      VARCHAR(128) NOT NULL DEFAULT '',
        n_atoms      INT NOT NULL DEFAULT 0,
        head_atom_id VARCHAR(64),
        tail_atom_id VARCHAR(64),
        centroid     MEDIUMBLOB,
        payload      MEDIUMTEXT NOT NULL,
        created_at   VARCHAR(64) NOT NULL,
        updated_at   VARCHAR(64) NOT NULL,
        PRIMARY KEY (id),
        KEY idx_chains_user (user_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS memcells (
        id              VARCHAR(64) NOT NULL,
        user_id         VARCHAR(128) NOT NULL DEFAULT '',
        session_id      VARCHAR(128),
        t_start         VARCHAR(64),
        t_end           VARCHAR(64),
        episode_type    VARCHAR(64) NOT NULL DEFAULT 'unknown',
        payload         MEDIUMTEXT NOT NULL,
        topic_embedding MEDIUMBLOB,
        PRIMARY KEY (id),
        KEY idx_cells_session (user_id, session_id),
        KEY idx_cells_type (user_id, episode_type, t_start)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS session_context (
        user_id     VARCHAR(128) NOT NULL DEFAULT '',
        session_id  VARCHAR(128) NOT NULL,
        summary     MEDIUMTEXT NOT NULL,
        covered     INT NOT NULL DEFAULT 0,
        updated_at  VARCHAR(64),
        PRIMARY KEY (user_id, session_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tasks (
        task_id     VARCHAR(64) NOT NULL,
        kind        VARCHAR(32) NOT NULL,
        user_id     VARCHAR(128) NOT NULL,
        session_id  VARCHAR(128) NOT NULL,
        status      VARCHAR(16) NOT NULL,
        result      MEDIUMTEXT,
        error       TEXT,
        created_at  VARCHAR(64) NOT NULL,
        updated_at  VARCHAR(64) NOT NULL,
        PRIMARY KEY (task_id),
        KEY idx_tasks_user (user_id),
        KEY idx_tasks_status (status, updated_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS profile_versions (
        id            VARCHAR(64) NOT NULL,
        user_id       VARCHAR(128) NOT NULL,
        version       INT NOT NULL,
        profile_json  MEDIUMTEXT NOT NULL,
        up_to_cell_id VARCHAR(64) NOT NULL DEFAULT '',
        created_at    DATETIME NOT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_user_version (user_id, version),
        KEY idx_user_created (user_id, created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS characters (
        id            VARCHAR(64) NOT NULL,
        user_id       VARCHAR(128) NOT NULL DEFAULT '',
        is_wearer     TINYINT NOT NULL DEFAULT 0,
        primary_name  VARCHAR(128) DEFAULT NULL,
        status        VARCHAR(16) NOT NULL DEFAULT 'active',
        merged_into   VARCHAR(64) DEFAULT NULL,
        face_tau      DOUBLE NOT NULL DEFAULT 0,
        voice_tau     DOUBLE NOT NULL DEFAULT 0,
        payload       MEDIUMTEXT,
        created_at    VARCHAR(64) NOT NULL,
        updated_at    VARCHAR(64) NOT NULL,
        PRIMARY KEY (id),
        KEY idx_char_user (user_id, status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS character_assets (
        id            VARCHAR(64) NOT NULL,
        user_id       VARCHAR(128) NOT NULL DEFAULT '',
        character_id  VARCHAR(64) NOT NULL,
        kind          VARCHAR(16) NOT NULL,
        quality       DOUBLE NOT NULL DEFAULT 0,
        embedding     MEDIUMBLOB,
        dim           INT DEFAULT NULL,
        status        VARCHAR(16) NOT NULL DEFAULT 'active',
        payload       MEDIUMTEXT,
        created_at    VARCHAR(64) NOT NULL,
        PRIMARY KEY (id),
        KEY idx_asset_char (user_id, character_id, kind, status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS character_cloud (
        id            VARCHAR(64) NOT NULL,
        user_id       VARCHAR(128) NOT NULL DEFAULT '',
        character_id  VARCHAR(64) NOT NULL,
        modality      VARCHAR(16) NOT NULL,
        slot          VARCHAR(16) NOT NULL,
        embedding     MEDIUMBLOB,
        dim           INT DEFAULT NULL,
        payload       MEDIUMTEXT,
        updated_at    VARCHAR(64) NOT NULL,
        PRIMARY KEY (id),
        KEY idx_cloud_char (user_id, character_id, modality, slot)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
